"""Handoff engine - regenerates the AI-onboarding view of a .pace/ instance.

Produces .pace/handoff/HANDOFF.md: the single file an AI reads first. It
names who governs the project, how to work here, the current mission /
vision / roadmap / sprint, the recent continuity notes, and a set of
health checks so the AI is proactively told what needs attention. The
handoff/ section is REGENERABLE: rebuilt from the authoritative sources.
"""

from pathlib import Path

from pace.services.pdl import read_pdl
from pace.engines.rules import load_rules

ACTIVE_SECTIONS = [
    ("Mission", "ACTIVE_MISSION"),
    ("Vision", "ACTIVE_VISION"),
    ("Roadmap", "ACTIVE_ROADMAP"),
    ("Current sprint", "ACTIVE_SPRINT"),
]

CONTINUITY_REL = "memory/persistent/CONTINUITY.md"


def _read_section(root, relative_path):
    if not relative_path:
        return "(not set)"
    full = root / relative_path
    if not full.is_file():
        return "(file not found)"
    return full.read_text(encoding="utf-8").strip()


def _count_pdl(root, section):
    d = root / section
    if not d.is_dir():
        return 0
    return sum(1 for p in d.iterdir() if p.is_file() and p.suffix == ".pdl")


def _root_authority(root):
    actors_dir = Path(root) / "actors"
    if not actors_dir.is_dir():
        return None
    for p in sorted(actors_dir.glob("*.pdl")):
        data = read_pdl(p)
        if str(data.get("IS_ROOT_AUTHORITY", "")).strip().lower() == "true":
            label = f"{data.get('ROLE', '')} {data.get('NAME', '')}".strip()
            return label or data.get("NAME")
    return None


def _continuity_notes(root):
    path = Path(root) / CONTINUITY_REL
    if not path.is_file():
        return []
    return [l for l in path.read_text(encoding="utf-8").splitlines() if l.strip().startswith("- ")]


def generate_handoff(root):
    root = Path(root)
    instance = read_pdl(root / "INSTANCE.pdl")
    active = read_pdl(root / "ACTIVE_VERSIONS.pdl")
    name = instance.get("NAME", "this project")
    kind = instance.get("KIND", "PROJECT")
    authority = _root_authority(root)
    contents = {key: _read_section(root, active.get(key)) for _, key in ACTIVE_SECTIONS}

    out = []
    out.append(f"# PACE Handoff - {name}")
    out.append("")
    out.append("You are an AI joining this project. Read this first: it is the")
    out.append("project's own memory, so you do not have to ask what we are doing")
    out.append("or why. This file is regenerated by PACE - do not edit it by hand.")
    out.append("")
    out.append("## How to work here")
    out.append("")
    if authority:
        out.append(f"- The ROOT_AUTHORITY of this project is **{authority}**.")
        out.append("  You ADVISE and AUDIT; they decide. Propose, never override.")
    else:
        out.append("- You ADVISE and AUDIT; the project owner (ROOT_AUTHORITY) decides.")
    out.append('- Update sections with `pace supersede <section> "..."` - never edit a')
    out.append("  versioned file in place. Log lasting notes with `pace remember`.")
    out.append("- Every approved correction becomes a rule you must follow. Do not")
    out.append("  re-ask what an approved rule already settles.")
    out.append("")
    rules = load_rules(root)
    out.append("## Rules you must follow")
    out.append("")
    if rules:
        out.append("Approved, permanent rules. Do not re-litigate or re-ask what these")
        out.append("already settle:")
        out.append("")
        current = None
        for r in rules:
            scope = r.get("SCOPE", "")
            if scope != current:
                out.append(f"**{scope}**")
                current = scope
            out.append(f"- {r.get('STATEMENT', '')}")
        out.append("")
    else:
        out.append('(no rules recorded yet - add with `pace rule add --scope PACE --statement "..."`)')
        out.append("")

    out.append("## Identity")
    out.append("")
    out.append(f"- Name: {name}")
    out.append(f"- Kind: {kind}")
    if instance.get("ORG_REF"):
        out.append(f"- Belongs to: {instance.get('ORG_REF')}")
    if authority:
        out.append(f"- Root authority: {authority}")
    out.append("")

    for label, key in ACTIVE_SECTIONS:
        out.append(f"## {label}")
        out.append("")
        out.append("```")
        out.append(contents[key])
        out.append("```")
        out.append("")

    notes = _continuity_notes(root)
    out.append("## Recent continuity notes")
    out.append("")
    if notes:
        out.append(f"The working log has {len(notes)} notes. Most recent below; read the")
        out.append(f"full detail in .pace/{CONTINUITY_REL}:")
        out.append("")
        out.extend(notes[-12:])
    else:
        out.append("(no continuity notes yet)")
    out.append("")

    out.append("## Where the rest of the memory lives")
    out.append("")
    out.append(f"- Decisions: .pace/decisions/  ({_count_pdl(root, 'decisions')} recorded)")
    out.append(f"- History:   .pace/history/    ({_count_pdl(root, 'history')} entries)")
    out.append(f"- Requests:  .pace/requests/   ({_count_pdl(root, 'requests')} logged in intake)")
    out.append("")

    warnings = []
    for label, key in ACTIVE_SECTIONS:
        c = contents[key]
        if ("Not yet defined" in c) or c in ("(not set)", "(file not found)"):
            sec = key.replace("ACTIVE_", "").lower()
            warnings.append(
                f"{label} is still a placeholder or missing - fill it with "
                f'`pace supersede {sec} "..."` or `pace init --guided`.'
            )
    if len(notes) > 30:
        warnings.append(
            f"The continuity log has {len(notes)} notes - run `pace condense` to "
            "archive the old ones (nothing discarded)."
        )
    out.append("## Health checks")
    out.append("")
    if warnings:
        for w in warnings:
            out.append(f"- WARN: {w}")
    else:
        out.append("- OK: no issues detected (all core sections filled).")
    out.append("")

    handoff_dir = root / "handoff"
    handoff_dir.mkdir(parents=True, exist_ok=True)
    path = handoff_dir / "HANDOFF.md"
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    return path
