"""Handoff engine - regenerates the AI-onboarding view of a .pace/ instance.

Produces .pace/handoff/HANDOFF.md: the single file an AI reads first. It
states who governs the project (whom to consult), how to work here, and the
current mission / vision / roadmap / sprint, plus pointers to the deeper
memory. The handoff/ section is REGENERABLE (disposable): this rebuilds it
from the authoritative sources, never the other way around.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from services.pdl import read_pdl

ACTIVE_SECTIONS = [
    ("Mission", "ACTIVE_MISSION"),
    ("Vision", "ACTIVE_VISION"),
    ("Roadmap", "ACTIVE_ROADMAP"),
    ("Current sprint", "ACTIVE_SPRINT"),
]


def _read_section(root: Path, relative_path):
    if not relative_path:
        return "(not set)"
    full = root / relative_path
    if not full.is_file():
        return "(file not found)"
    return full.read_text(encoding="utf-8").strip()


def _count_pdl(root: Path, section: str) -> int:
    d = root / section
    if not d.is_dir():
        return 0
    return sum(1 for p in d.iterdir() if p.is_file() and p.suffix == ".pdl")


def generate_handoff(root: Path) -> Path:
    """Rebuild .pace/handoff/HANDOFF.md from the instance. Returns its path."""
    root = Path(root)
    instance = read_pdl(root / "INSTANCE.pdl")
    active = read_pdl(root / "ACTIVE_VERSIONS.pdl")
    name = instance.get("NAME", "this project")
    kind = instance.get("KIND", "PROJECT")

    out = []
    out.append(f"# PACE Handoff - {name}")
    out.append("")
    out.append("You are an AI joining this project. Read this first: it is the")
    out.append("project's own memory, so you do not have to ask what we are doing")
    out.append("or why. This file is regenerated by PACE - do not edit it by hand.")
    out.append("")
    out.append("## How to work here")
    out.append("")
    out.append("- You ADVISE and AUDIT; the project owner (ROOT_AUTHORITY) decides.")
    out.append("  Propose, never override. Confirm with the owner before anything")
    out.append("  becomes official.")
    out.append("- Every permanent correction is logged as a request and, once")
    out.append("  approved, becomes a rule you must follow. Do not re-ask what an")
    out.append("  approved rule already settles.")
    out.append("")
    out.append("## Identity")
    out.append("")
    out.append(f"- Name: {name}")
    out.append(f"- Kind: {kind}")
    if instance.get("ORG_REF"):
        out.append(f"- Belongs to: {instance.get('ORG_REF')}")
    out.append("")

    for label, key in ACTIVE_SECTIONS:
        out.append(f"## {label}")
        out.append("")
        out.append("```")
        out.append(_read_section(root, active.get(key)))
        out.append("```")
        out.append("")

    out.append("## Where the rest of the memory lives")
    out.append("")
    out.append(f"- Decisions: .pace/decisions/  ({_count_pdl(root, 'decisions')} recorded)")
    out.append(f"- History:   .pace/history/    ({_count_pdl(root, 'history')} entries)")
    out.append(f"- Requests:  .pace/requests/   ({_count_pdl(root, 'requests')} logged in intake)")
    out.append("")
    out.append("Read those for the WHY behind decisions and the reasoning that is")
    out.append("not in the code - including paths that were tried and discarded.")
    out.append("")

    handoff_dir = root / "handoff"
    handoff_dir.mkdir(parents=True, exist_ok=True)
    path = handoff_dir / "HANDOFF.md"
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    return path
